# Generated by Django 4.2 on 2026-02-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_cook_time_remove_recipe_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipecategory'),
            preserve_default=False,
        ),
    ]
